config:
  backup: true
  banner: true
  create: true
  dotpath: .dots
  ignoreempty: false
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: link
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  d_bin:
    dst: ~/.bin
    link: link
    src: bin
  d_bspwm:
    dst: ~/.config/bspwm
    link: link
    src: config/bspwm
  d_doom:
    dst: ~/.doom.d
    link: link
    src: doom
  d_dunst:
    dst: ~/.config/dunst
    link: link
    src: config/dunst
  d_emacs:
    dst: ~/.emacs.d
    link: link
    src: emacs
  d_i3:
    dst: ~/.config/i3
    link: link
    src: config/i3
  d_mpd:
    dst: ~/.config/mpd
    link: link
    src: config/mpd
  d_networkmanager-dmenu:
    dst: ~/.config/networkmanager-dmenu
    link: link
    src: config/networkmanager-dmenu
  d_polybar:
    dst: ~/.config/polybar
    link: link
    src: config/polybar
  d_qutebrowser:
    dst: ~/.config/qutebrowser
    link: link
    src: config/qutebrowser
  d_ranger:
    dst: ~/.config/ranger
    link: link
    src: config/ranger
  d_rofi:
    dst: ~/.config/rofi
    link: link
    src: config/rofi
  d_rofi-pass:
    dst: ~/.config/rofi-pass
    link: link
    src: config/rofi-pass
  d_sxhkd:
    dst: ~/.config/sxhkd
    link: link
    src: config/sxhkd
  d_teiler:
    dst: ~/.config/teiler
    link: link
    src: config/teiler
  d_walls:
    dst: ~/.config/walls
    link: link
    src: walls
  f_compton.conf:
    dst: ~/.compton.conf
    link: link
    src: compton.conf
  f_editorconfig:
    dst: ~/.editorconfig
    link: link
    src: editorconfig
  f_ncmpcpp:
    dst: ~/.config/ncmpcpp
    link: link
    src: config/ncmpcpp
  f_rtorrent:
    dst: ~/.rtorrent.rc
    link: link
    src: rtorrent.rc
  f_safe-rm:
    dst: ~/.config/safe-rm
    link: link
    src: config/safe-rm
  f_tmux:
    dst: ~/.tmux.conf
    link: link
    src: tmux.conf
  f_xprofile:
    dst: ~/.xprofile
    link: link
    src: xprofile
  f_xresources:
    dst: ~/.Xresources
    link: link
    src: Xresources
  f_zaturarc:
    dst: ~/.config/zathura/zathurarc
    link: link
    src: config/zathura/zathurarc
  f_zshrc:
    dst: ~/.zshrc
    link: link
    src: zshrc
  f_xonshrc:
    src: xonshrc
    dst: ~/.xonshrc
    link: link
profiles:
  Pantheon:
    dotfiles:
    - d_bin
    - d_bspwm
    - d_doom
    - d_dunst
    - d_i3
    - d_mpd
    - d_networkmanager-dmenu
    - d_polybar
    - d_qutebrowser
    - d_ranger
    - d_rofi
    - d_rofi-pass
    - d_sxhkd
    - f_ncmpcpp
    - f_rtorrent
    - f_tmux
    - f_xonshrc
    - f_xprofile
    - f_xresources
