# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

# pylint: disable=C0111
c = c  # noqa: F821 pylint: disable=E0602,C0103
config = config  # noqa: F821 pylint: disable=E0602,C0103

# Enable JavaScript.
# Type: Bool
config.set("content.javascript.enabled", True, "file://*")

# Enable JavaScript.
# Type: Bool
config.set("content.javascript.enabled", True, "chrome://*/*")

# Enable JavaScript.
# Type: Bool
config.set("content.javascript.enabled", True, "qute://*/*")

config.bind("<z><p><f>", "spawn --userscript password_fill")

# When to show the tab bar.
# Type: String
# Valid values:
#   - always: Always show the tab bar.
#   - never: Always hide the tab bar.
#   - multiple: Hide the tab bar if only one tab is open.
#   - switching: Show the tab bar when switching tabs.
c.tabs.show = "never"

# Font used in the completion widget.
# Type: Font
c.fonts.completion.entry = "bold 9pt mononoki NF"

# Font used in the completion categories.
# Type: Font
c.fonts.completion.category = "bold 9pt mononoki NF"

# Font used for prompts.
# Type: Font
c.fonts.prompts = "9pt mononoki NF"

# Font used in the statusbar.
# Type: Font
c.fonts.statusbar = "9pt mononoki NF"
