#!/usr/bin/env sh
#
# bspwm hotkeys
#

# Apps

# Program Launcher
super + space
  ~/.bin/rofi-run

# Clipboard
super + shift + c
  ~/.bin/rofi-clip

# Password Manager
super + shift + period
  rofi-pass

# Screen Manager
super + F8
  ~/.bin/rofi-xrandr

# Window Switch
super + Tab
  rofi -show window -width 36

# Exit Menu
super + Escape
  ~/.bin/rofi-exit

# Take Screenshot
Print
  teiler

# Restart bspwm
super + shift + r
  ~/.config/bspwm/bspwmrc

# Terminal
super + Return
  urxvtcd -g 100x30 -name terminal

# Cli Apps
super + shift + {f,i}
  urxvtcd {-name ranger -e ranger, -name chat -e weechat}

# Volume
alt + {m,Up,Down}
  pamixer {-t,-i 1,-d 1}

# Reload Funtions
super + shift + Escape
  pkill -USR1 -x sxhkd

# Mouse Focus
~button1
  bspc node pointed -f

#
# bspwm hotkeys
#

# close and kill
super + w
  bspc node -c

# alternate between the tiled and monocle layout
super + m
  bspc desktop -l next

# if the current node is automatic, send it to the last manual, otherwise pull the last leaf
super + y
  bspc query -N -n focused.automatic && bspc node -n last.!automatic || bspc node last.leaf -n focused

# swap the current node and the biggest node
super + g
  bspc node -s bigges

#
# state/flags
#

# set the window state
super + {t,shift + t,s,f}
  bspc node -t {tiled,pseudo_tiled,floating,fullscreen}

# set the node flags
super + ctrl + {x,y,z}
  bspc node -g {locked,sticky,private}

#
# focus/swap
#

# Flip layout vertically/horizontally
super + {_,shift + }s
	bspc node @/ --flip {vertical,horizontal}

# focus the node in the given direction
super + {_,shift + }{h,j,k,l}
  bspc node -{f,s} {west,south,north,east}

# focus the node for the given path jump
super + {p,b,comma,period}
  bspc node -f @{parent,brother,first,second}

# focus the next/previous node in the current desktop
super + {_,shift + }c
  bspc node -f {next,prev}.local

# focus the next/previous desktop in the current monitor
super + bracket{left,right}
  bspc desktop -f {prev,next}.local

# focus the last node/desktop
super + {grave,Tab}
  bspc {node,desktop} -f last

# focus the older or newer node in the focus history
super + {o,i}
  bspc wm -h off; \
  bspc node {older,newer} -f; \
  bspc wm -h on

# focus or send to the given desktop
super + {_,shift + }{0-9}
  bspc {desktop -f,node -d} '^{0-9}'

#
# preselect
#

# preselect the direction
super + ctrl + {h,j,k,l}
  bspc node -p {west,south,north,east}

# preselect the ratio
super + ctrl + {1-9}
  bspc node -o 0.{1-9}

# cancel the preselection for the focused node
super + ctrl + space
  bspc node -p cancel

# cancel the preselection for the focused desktop
super + ctrl + shift + space
  bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel

#
# move/resize
#

# expand a window by moving one of its side outward
super + alt + {h,j,k,l}
  bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# contract a window by moving one of its side inward
super + alt + shift + {h,j,k,l}
  bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# move a floating window
super + {Left,Down,Up,Right}
  bspc node -v {-20 0,0 20,0 -20,20 0}

# Move window to left/right desktop
ctrl + alt + shift + {Left,Right}
	bspc node --to-desktop {prev,next} --focus

# Move window to left/right desktop
ctrl + alt + shift + {Down,Up}
    bspc node -d {next,prev}; \
    bspc desktop -f {next,prev}
